# Generated by Django 5.0.4 on 2024-04-17 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casas',
            options={'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterModelOptions(
            name='edificios',
            options={'verbose_name_plural': 'Edificios'},
        ),
        migrations.AlterModelOptions(
            name='fincas',
            options={'verbose_name_plural': 'Fincas'},
        ),
        migrations.AlterModelOptions(
            name='propietarios',
            options={'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AddField(
            model_name='casas',
            name='barrio',
            field=models.CharField(max_length=255, null=True, verbose_name='Barrio'),
        ),
        migrations.AddField(
            model_name='edificios',
            name='nombre',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre del edificio'),
        ),
        migrations.AddField(
            model_name='fincas',
            name='nombre',
            field=models.CharField(max_length=255, null=True, verbose_name='Nombre de la finca'),
        ),
        migrations.AddField(
            model_name='propietarios',
            name='apellido',
            field=models.CharField(max_length=255, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='añocontruccion',
            field=models.CharField(max_length=255, verbose_name='Año de construcción'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='numerohabitaciones',
            field=models.CharField(max_length=255, verbose_name='Número de habitaciones'),
        ),
        migrations.AlterField(
            model_name='casas',
            name='tipocontruccion',
            field=models.CharField(choices=[('tradicional', 'Tradicional'), ('moderno', 'Moderno')], max_length=255, verbose_name='Tipo de construcción'),
        ),
        migrations.AlterField(
            model_name='edificios',
            name='añoconstruccion',
            field=models.CharField(max_length=255, verbose_name='Año de construccion'),
        ),
        migrations.AlterField(
            model_name='edificios',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='edificios',
            name='estadoedificio',
            field=models.CharField(max_length=255, verbose_name='Estado del edificio'),
        ),
        migrations.AlterField(
            model_name='edificios',
            name='tipoedificio',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('oficinas', 'Oficinas')], max_length=255, verbose_name='Tipo de edificio'),
        ),
        migrations.AlterField(
            model_name='fincas',
            name='actividad',
            field=models.CharField(choices=[('agricultura', 'Agricultura'), ('ganaderia', 'Ganadería'), ('forestal', 'Forestal')], max_length=255, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='fincas',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='fincas',
            name='infraestructura',
            field=models.CharField(max_length=255, verbose_name='Infraestructura'),
        ),
        migrations.AlterField(
            model_name='fincas',
            name='tamañoterreno',
            field=models.CharField(max_length=255, verbose_name='Tamaño del terreno'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='cedula',
            field=models.CharField(max_length=255, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='celular',
            field=models.CharField(max_length=255, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='idcasas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_casas_list', to='inmobiliaria_app.casas', verbose_name='Casa en propiedad'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='idedificios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_edificios_list', to='inmobiliaria_app.edificios', verbose_name='Edificio en propiedad'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='idfincas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_fincas_list', to='inmobiliaria_app.fincas', verbose_name='Finca en propiedad'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
    ]
