# Generated by Django 5.0.4 on 2024-04-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_app', '0002_alter_casas_options_alter_edificios_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fincas',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='fincas',
            name='actividad',
            field=models.CharField(choices=[('agricultura', 'Agricultura'), ('ganaderia', 'Ganadería'), ('mixto', 'Mixto')], max_length=255, verbose_name='Actividad'),
        ),
    ]
