# Generated by Django 5.0.4 on 2024-04-18 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmobiliaria_app', '0003_remove_fincas_direccion_alter_fincas_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietarios',
            name='idcasas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_casas_list', to='inmobiliaria_app.casas', verbose_name='Casa en propiedad'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='idedificios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_edificios_list', to='inmobiliaria_app.edificios', verbose_name='Edificio en propiedad'),
        ),
        migrations.AlterField(
            model_name='propietarios',
            name='idfincas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propietarios_fincas_list', to='inmobiliaria_app.fincas', verbose_name='Finca en propiedad'),
        ),
    ]
